### ISSUE TITLE
deiconify won't delete cache thumnail

### ISSUE THREAD

**Issue by heelsleeh** [Minda1975/FVWM#1]
it seems doesn't execute *FvwmEvent deiconify DeThumbnail

**Comment by Minda1975** [comment]
> it seems doesn't execute *FvwmEvent deiconify DeThumbnail

Hello. I delete them manually. In addition, cache thumnail do not take up much space. I use this configuration for about two months. It takes about 2 MB disk space. I do not know how to force it to do it automatically.

**Comment by heelsleeh** [comment]
thanks for reply, i'v figured it out how to works, here is the way:
change *FvwmEvent to *FirstEvent  like this
`*FirstEvent: deiconify DeThumbnail`
add FirstEvent to StartFunction
`+I Module FvwmEvent FirstEvent`
done

**Comment by Minda1975** [comment]
> done

Hello again. Thank you for solving this problem. Everything works normally, as it should work. I updated the configuration file.
